backend:
  name: git-gateway
  branch: main

# Publish mode - simple for direct publishing
publish_mode: simple

# Media files
media_folder: "public/static/images"
public_folder: "/static/images"

# Site URL
site_url: https://blog.gelora.study
display_url: https://blog.gelora.study

# Logo
logo_url: /static/images/logo-128.png

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "SEO-friendly post title"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["ethereum"], hint: "Tags: ethereum, defi, protocol, education, etc."}
      - {label: "Summary", name: "summary", widget: "text", hint: "Brief description (appears in previews and SEO)"}
      - {label: "Featured Image", name: "coverImage", widget: "image", required: false, hint: "Header image (recommended: 1200x630px)"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false, hint: "Save as draft or publish immediately"}
      - {label: "Content", name: "body", widget: "markdown", hint: "Write your article content here. Supports Markdown formatting."}

  - name: "authors"
    label: "Authors"
    folder: "data/authors"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Twitter", name: "twitter", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "GitHub", name: "github", widget: "string", required: false}

# Editor preview
editor:
  preview: true

# Slug configuration
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
